FROM python:3.10-bullseye
RUN python -m pip install --upgrade pip

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.11.0/wait /wait
RUN chmod +x /wait

WORKDIR /app
COPY ./requirements.txt requirements.txt
RUN python -m pip install -r requirements.txt

# Automatically run migrations during development. We never want to do this in production.
# Commands are to wait for the database to start up, run migrations, then
# start our webserver. We use the --reload flag, because we want uvicorn (our web server)
# to watch our python files and reload the application whenever we make a change.
#
# uvicorn is running "main:app". 'main' is the name of the file (main.py), and 'app' is
# the variable inside that file it's going to run.
CMD /wait && python -m migrations up && uvicorn main:app --reload --host 0.0.0.0 --port $PORT
